import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Link from "next/link";

const Home: NextPage = () => {
  const { data } = trpc.useQuery(["bookings.getAll"]);
  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-blue-500 text-center text-3xl">Book a repair</h1>
        <div className="flex justify-center">
          <Link href="/createForm">
            <a className="text-blue-500 hover:text-blue-800 border px-4 py-3 rounded">
              Create New Booking
            </a>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
